### ISSUE TITLE
extra parameters to "path:"

### ISSUE THREAD

**Issue by riebling** [andreasplesch/aframe-meshline-component#13]
The example in README shows path being set in HTML as:
```
<a-entity meshline="lineWidth: 20; path: -2 -1 0, 0 -2 0, 2 -1; color: #E20049"></a-entity>
```
What are the extra `2 -1` after the two coordinates `-2 -1 0, 0 -2 0` ? My guess is they are lineWidth and lineWidthStyler, but those labels are apparently omitted / optional. The example could be more clear if these are spelled out, especially for someone new to the mysteries of mixed Javascript / HTML / CSS / JSON syntax. It's OK that (meshline) Component declarations consist of semicolon separated keyword-value pairs, where keyword-value is colon separated, and values are ... a mixture of space and comma separated?

**Comment by riebling** [comment]
As a super-duper extra bonus, how would an equivalent to the example be specified for programmatically defining a meshline in Javascript via setAttribute()?

**Comment by andreasplesch** [comment]
As far as I remember the extra parameters 2 -1 were added to test how robust Aframe's coordinate parsing is, and if it is necessary to check for malformed coordinates. This component was my learning component. It looks like such incomplete points in a path have zeroes filled in for missing values.

The declaration otherwise just follows AFrame standards which is along the lines you described.

An example with the lineWidthStyler property looks like this:
```html
<a-entity meshline="
  lineWidth: 20; 
  path: -2 -1 0, 0 -2 0, 2 -1 0; 
  color: #E20049;
  lineWidthStyler: Math.sin( p * 3.14 )">
</a-entity>
```

AFrame redefines .get/setAttribute to return/use a js object rather than strings for more convenient manipulation if provided: https://aframe.io/docs/0.9.0/introduction/javascript-events-dom-apis.html#modifying-an-entity

But you also could just construct a meshline attribute string value by hand.

**Comment by andreasplesch** [comment]
Here is an example of how to modify or construct lines programmatically:

https://jsitor.com/SzH16a7KC?html&result

Interesting that stringify is not called anymore.

**Comment by riebling** [comment]
Wow, thanks! I've managed to get thicklines working for our app (which draws lines to represent bones of 3d skeleton body capture in realtime) Your info is helpful.

**Comment by riebling** [comment]
didn't even notice the coolest part, the path can have more than one line segment; this might add some efficiency rather than using multiple, separate line objects

**Comment by richardcck** [comment]
Dear all

in "https://jsitor.com/SzH16a7KC?html&result"

I found below message, is it normal?

"A-Frame:warn Put the A-Frame 
A-Frame Version: 0.9.2 (Date 2019-05-06, Commit #f57a1fa)
three Version (https://github.com/supermedium/three.js):
^0.102.2
WebVR Polyfill Version:
^0.10.10
THREE.WebGLRenderer
103dev
core:a-node:error Failure loading node:  
{ this.geometry.setAttribute is not a function }
core:a-node:error Failure loading node:  
{ this.geometry.setAttribute is not a function }
core:a-node:error Failure loading node:  
{ this.geometry.setAttribute is not a function }
Script error."
